language: php

addons:
  chrome: stable

php:
  - 7.1

cache:
  directories:
    - ~/.composer/cache
    - ~/cphalcon

install:
  - composer install --no-interaction
  - vendor/bin/install-phalcon.sh 3.0.x
  - chmod +x tests/drivers/chromedriver-linux

script:
  - composer run-script tests
