language: php
php:
  - 7.2

sudo: required
dist: trusty

addons:
   chrome: stable
   ssh_known_hosts: deplink.org

install:
   - cp .env.travis .env
   - mysql -e 'create database dusk;'
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
   - php artisan serve &

script:
   - php artisan dusk
   - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then bash ./deploy.sh; fi
