language: php
php:
  - 7.2

sudo: required
dist: trusty

addons:
   chrome: stable

install:
   - cp .env.travis .env
   - mysql -e 'create database dusk character set utf8 collate utf8_general_ci;'
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
   - php artisan serve &

script:
   - php artisan dusk
