dist: trusty

sudo: required

language: php

addons:
  chrome: stable

php:
  - 7.1

before_install:
  - chmod +x tests/bin/chromedriver-linux
  - vendor/bin/install-phalcon.sh 3.0.x

install:
  - composer install --no-interaction

script:
  - composer run-script tests
