language: php

sudo: required

addons:
  chrome: stable

php:
  - 7.0

cache:
  directories:
    - ~/.composer/cache

install:
  - curl -s "https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh" | sudo bash
  - sudo apt-get install php7.0-phalcon
  - composer install --no-interaction
  - chmod +x tests/drivers/chromedriver-linux

script:
  - composer run-script tests
