dist: trusty
language: php
addons:
  chrome: stable

php:
  - 7.1

before_install:
  - google-chrome-stable --headless --disable-gpu http://localhost:8000 &

install:
  - composer install --no-interaction

script:
  - composer run-script tests
